export const REPORT_CREATE = "REPORT_CREATE";
export const REPORT_UPDATE = "REPORT_UPDATE";
export const REPORT_DELETE = "REPORT_DELETE";
export const REPORT_DELETE_ALL = "REPORT_DELETE_ALL";
export const REPORT_FETCH_ALL = "REPORT_FETCH_ALL";